### ISSUE TITLE
iMessageClone can't launch

### ISSUE THREAD

**Issue by ryskin** [GetStream/react-native-samples#27]
I can't install packages using npm (npm ERR! code EINVALIDTAGNAME)
After running have the error "[Error: StreamChat error code 4: QueryChannels failed with error: "field "members" expects array element of type string"]" and in the application, channel list can't be loaded.

**Comment by vanGalilea** [comment]
@ryskin, we have updated the iMessage clone and have done extensive maintenance. We will be closing this issue for now, don't hesitate to reach out if you have any questions or thoughts!
